# The Chosen Dataset
- We chose a dataset, fitting the real-life problems, indicating the levels of burnout predicted according to the environment surrounding the employees.

- Source: https://www.kaggle.com/datasets/asifxzaman/developer-burnout-prediction-dataset7000-samples

# TASK #1

In [189]:
import numpy as np
import pandas as pd
df = pd.read_excel('data.xlsx')
df.shape

(22750, 9)

In [190]:
df.sample(20)

,Employee ID,Date of Joining,Gender,Company Type,WFH Setup Available,Designation,Resource Allocation,Mental Fatigue Score,Burn Rate
13078,fffe3500360034003400,2008-10-31,Female,Product,No,2,3.0,5.4,0.50
4012,fffe33003100380032003500,2008-07-10,Female,Service,Yes,4,9.0,8.8,0.77
7953,fffe31003200350030003300,2008-04-20,Male,Service,No,3,7.0,8.8,0.91
8572,fffe32003300300030003300,2008-02-01,Female,Service,Yes,3,7.0,8.5,0.81
19085,fffe3700310031003300,2008-08-09,Male,Product,Yes,1,3.0,5.3,0.47
6631,fffe3700320039003200,2008-06-04,Male,Product,Yes,1,4.0,4.4,0.32
11616,fffe31003100310035003700,2008-09-04,Female,Service,Yes,2,3.0,6.1,0.44
8258,fffe31003300360030003200,2008-02-10,Male,Product,No,4,NaN,NaN,0.75
6015,fffe32003800330030003300,2008-09-14,Female,Service,No,3,6.0,7.3,0.59
1385,fffe33003400330038003300,2008-11-25,Female,Product,Yes,1,3.0,4.4,0.35
3310,fffe31003600390035003900,2008-01-01,Female,Service,Yes,2,NaN,4.7,0.23
2410,fffe32003600330035003900,2008-05-07,Female,Product,No,1,2.0,4.9,0.31
13530,fffe3100350037003500,2008-02-20,Female,Product,Yes,3,7.0,7.0,0.71
14525,fffe390037003300,2008-01-12,Male,Service,No,2,4.0,1.9,0.12
1671,fffe33003100300030003200,2008-03-26,Male,Service,Yes,1,2.0,6.1,0.38
8969,fffe33003100320037003200,2008-10-07,Male,Service,No,2,4.0,5.6,0.32
15015,fffe31003100340033003000,2008-09-18,Female,Service,Yes,3,5.0,5.6,0.37
4457,fffe31003200380030003900,2008-05-28,Male,Product,No,2,6.0,6.5,0.51
16114,fffe3300380036003900,2008-12-01,Male,Product,No,4,6.0,7.3,0.66
9154,fffe31003300320038003200,2008-09-22,Male,Product,Yes,2,3.0,3.1,0.19

In [191]:
print(df.dtypes)
df.info()

Employee ID                        str
Date of Joining         datetime64[us]
Gender                             str
Company Type                       str
WFH Setup Available                str
Designation                      int64
Resource Allocation            float64
Mental Fatigue Score           float64
Burn Rate                      float64
dtype: object
<class 'pandas.DataFrame'>
RangeIndex: 22750 entries, 0 to 22749
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Employee ID           22750 non-null  str
 1   Date of Joining       22750 non-null  datetime64[us]
 2   Gender                22750 non-null  str
 3   Company Type          22750 non-null  str
 4   WFH Setup Available   22750 non-null  str
 5   Designation           22750 non-null  int64
 6   Resource Allocation   21369 non-null  float64
 7   Mental Fatigue Score  20633 non-null  float64
 8   Burn Rate             21626 non-null  float64
dtypes: datetime64[us](1), float64(3), int64(1), str(4)
memory usage: 1.6 MB

In [195]:
df.describe()

,Date of Joining,Designation,Resource Allocation,Mental Fatigue Score,Burn Rate
count,22750,22750.000000,21369.000000,20633.000000,21626.000000
mean,2008-07-01 09:28:05.274725,2.178725,4.481398,5.728188,0.452005
min,2008-01-01 00:00:00,0.000000,1.000000,0.000000,0.000000
25%,2008-04-01 00:00:00,1.000000,3.000000,4.600000,0.310000
50%,2008-07-02 00:00:00,2.000000,4.000000,5.900000,0.450000
75%,2008-09-30 00:00:00,3.000000,6.000000,7.100000,0.590000
max,2008-12-31 00:00:00,5.000000,10.000000,10.000000,1.000000
std,NaN,1.135145,2.047211,1.920839,0.198226